// AUTO-GENERATED by scripts/fetch-holidays.mjs — DO NOT EDIT
// 由 prebuild 钩子在构建时刷新。手工改动会被覆盖。

import type { HolidayYear } from '../../utils/holiday';

import y2026 from './2026.json';
import y2027 from './2027.json';

export const ALL_HOLIDAYS: HolidayYear[] = [y2026, y2027];
